CREATE DATABASE ZEPTO_SQL_PROJECT ;  
USE ZEPTO_SQL_PROJECT ;
CREATE TABLE ZEPTO (

CATEGORY VARCHAR(150),
NAME VARCHAR(150) NOT NULL ,
MRP NUMERIC (8,2),
DISCOUNT_PERCENT NUMERIC (8,2) ,
AVAILABLE_QUANTITY INT ,
DISCOUNTED_SELLING_PRICE NUMERIC(8,2) ,
WEIGHT_IN_GRAMS INT ,
OUT_OF_STOCK BOOLEAN ,
QUANTITY INT 
);
SELECT * FROM ZEPTO LIMIT 5000 ; 
ALTER TABLE ZEPTO ADD ID SERIAL primary KEY FIRST ;

SELECT COUNT(*) FROM ZEPTO ;
-- CHECKING FOR NULL VALES.

SELECT * FROM ZEPTO WHERE 
NAME IS NULL 
OR 
CATEGORY IS NULL 
OR 
MRP IS NULL 
OR 
DISCOUNT_PERCENT IS NULL 
OR 
AVAILABLE_QUANTITY IS NULL 
OR 
DISCOUNTED_SELLING_PRICE IS NULL 
OR 
WEIGHT_IN_GRAMS IS NULL 
OR 
OUT_OF_STOCK IS NULL 
OR 
QUANTITY IS NULL ;

-- DIFFERENT PRODECT CATEGORY 

SELECT DISTINCT CATEGORY FROM ZEPTO ORDER BY CATEGORY ;  

-- PRODUCT IN STOCK VS OUT OF STOCK 

SELECT OUT_OF_STOCK , COUNT(*) FROM ZEPTO GROUP BY OUT_OF_STOCK ; 

-- PRODUCT NAME PRESENT MULTIPLES TIME 
SELECT NAME , COUNT(*) FROM ZEPTO GROUP BY NAME HAVING COUNT(*) > 1 ORDER BY COUNT(*) DESC ;

-- DATA CLEANING 
 -- PRODUCT WITH PRICE = 0 
 SELECT * FROM ZEPTO WHERE MRP = 0 OR DISCOUNTED_SELLING_PRICE = 0  ;
 
 DELETE FROM ZEPTO WHERE MRP = 0 ;
 SET SQL_SAFE_UPDATES = 0 ;
 
 -- CONVERT PAISE TO RUPEES 
  
UPDATE ZEPTO 
SET MRP = MRP/100.00, 
DISCOUNTED_SELLING_PRICE = DISCOUNTED_SELLING_PRICE / 100.00 ;

SELECT MRP , DISCOUNTED_SELLING_PRICE FROM ZEPTO ; 
 
 -- BUSSINESS INSIGHT QUERIES 
 
-- Q1. Find the top 10 best-value products based on the discount percentage.
SELECT DISTINCT NAME , MRP , DISCOUNT_PERCENT FROM ZEPTO ORDER BY  DISCOUNT_PERCENT DESC LIMIT 10 ;  

-- Q2.What are the Products with High MRP but Out of Stock
SELECT DISTINCT NAME ,MRP FROM ZEPTO WHERE OUT_OF_STOCK = 1 AND MRP > 300 ORDER BY MRP DESC ; 
  

-- Q3.Calculate Estimated Revenue for each category
SELECT DISTINCT CATEGORY , SUM(DISCOUNTED_SELLING_PRICE * AVAILABLE_QUANTITY ) AS Estimated_Revenue FROM ZEPTO GROUP BY CATEGORY ORDER BY Estimated_Revenue  ; 

-- Q4. Find all products where MRP is greater than 500 and discount is less than 10%.
SELECT DISTINCT NAME , MRP , DISCOUNT_PERCENT FROM ZEPTO  WHERE MRP > 500 AND DISCOUNT_PERCENT < 10 ; 

-- Q5. Identify the top 5 categories offering the highest average discount percentage.
SELECT CATEGORY  , AVG(DISCOUNT_PERCENT) AS AVG_DIS_PERCENT  FROM ZEPTO  GROUP BY CATEGORY ORDER BY AVG_DIS_PERCENT DESC LIMIT 5 ; 

-- Q6. Find the price per gram for products above 100g and sort by best value.
 SELECT DISTINCT NAME , WEIGHT_IN_GRAMS , DISCOUNTED_SELLING_PRICE , (DISCOUNTED_SELLING_PRICE / WEIGHT_IN_GRAMS) AS PRICE_PER_GM FROM ZEPTO 
 WHERE WEIGHT_IN_GRAMS >= 100 ORDER BY PRICE_PER_GM ; 

-- Q7.Group the products into categories like Low, Medium, Bulk.
  SELECT DISTINCT NAME  , WEIGHT_IN_GRAMS,
  CASE 
  WHEN WEIGHT_IN_GRAMS < 1000 THEN 'LOW'
  WHEN WEIGHT_IN_GRAMS < 5000 THEN 'Medium' 
  ELSE 'Bulk' 
  END AS WEIGHT_CATEGORY 
  FROM ZEPTO ;  
  
-- 08.What is the Total Inventory Weight Per Category
SELECT distinct CATEGORY  , SUM(WEIGHT_IN_GRAMS * AVAILABLE_QUANTITY ) AS TOTOAL_WEIGHT  FROM ZEPTO GROUP  BY CATEGORY ORDER BY TOTOAL_WEIGHT ; 
 
 


